.TH evilwm 1 "February 13, 2006" "" ""
.SH NAME
evilwm \- Minimalist Window Manager for X
.SH SYNOPSIS
.B evilwm [ \-display
.I display
.B ] [ \-term
.I termprog
.B ] [ \-fn
.I fontname
.B ] [ \-fg
.I foreground colour
.B ] [ \-fc
.I fixed colour
.B ] [ \-bg
.I background colour
.B ] [ \-bw
.I borderwidth
.B ] [ \-snap
.I num
.B ] [ \-mask1
.I modifiers
.B ] [ \-mask2
.I modifiers
.B ] [ \-altmask
.I modifier
.B ] [ [ \-app
.I name/class
.B [ \-g
.I geometry
.B ] [ \-v
.I vdesk
.B ] [ \-s ] ]...
.B [ \-nosoliddrag ]
.B [ \-V ]
.SH DESCRIPTION
.B evilwm
is a minimalist window manager based on aewm, extended to feature
many keyboard controls, and otherwise altered to be more friendly.
.PP
In
.BR evilwm ,
the focus follows the mouse pointer, and focus is not lost if
you stray onto the root window.  The current window border is shaded
gold, with other windows left as a dark grey.
.PP
You can use the mouse to manipulate windows either by click/dragging
the 1 pixel border, or by holding down Alt and doing so anywhere in the
client window. The controls are:
.IP "Button 1"
Move window.
.IP "Button 2"
Resize window.
.IP "Button 3"
Lower window.
.PP
Most keyboard controls are used by holding down Control and Alt, then
pressing a key. Available functions are:
.IP Return
Spawn new terminal.
.IP Escape
Delete current window.  Hold Shift as well to force kill a client.
.IP Insert
Lower current window.
.IP "H, J, K, L"
Move window left, down, up or right (16 pixels).  Holding Shift resizes the
window instead.
.IP "Y, U, B, N"
Move window to top-left, top-right, bottom-left or
bottom-right of screen.
.IP I
Show information about current window.
.IP Equals
Maximise current window vertically (toggle).
.IP X
Maximise current window (toggle).
.PP
If compiled with virtual desktop support, these functions are also available: 
.IP F
Fix or unfix current window.
.IP "1--8"
Switch virtual desktop.
.IP Left
Previous virtual desktop.
.IP Right
Next virtual desktop.
.PP
In addition to the above, Alt+Tab can be used to cycle through windows
on screen.
.PP
To make 
.B evilwm
exit, you have to kill the process.
.SH OPTIONS
.IP "\-display display"
specifies the X display to run on.
.IP "\-term termprog"
specifies an alternative program to run when spawning a new terminal (defaults
to xterm, or x\-terminal\-emulator in Debian).
.IP "\-fn fontname"
specify a font to use when resizing or displaying window titles.
.IP "\-fg foreground colour"
frame colour of currently active window.
.IP "\-fc fixed colour"
frame colour of active fixed windows.
.IP "\-bg background colour"
frame colour of inactive windows.
.IP "\-bw borderwidth"
width of window borders in pixels.
.IP "\-snap num"
enable snap-to-border support.  num gives the proximity in pixels to snap to.
.IP "\-mask1 modifiers"
.IP "\-mask2 modifiers"
.IP "\-altmask modifier"
override the default keyboard modifiers used to grab keys for window manager
functionality.
.I mask1
is used for most keyboard controls (default: control+alt), and
.I mask2
is used for mouse button controls and cycling windows (default: alt).
.I altmask
is used to modify the behaviour of certain controls (default: shift).
Modifiers may be separated with + signs.  Valid modifiers are shift, lock,
control, alt, mod1, mod2, mod3, mod4, mod5.
.IP "\-app name/class"
match an application by instance name and class (for help in finding these,
use the
.BR xprop
tool to extract the
.I WM_CLASS
property).  Subsequent
.I \-g, \-s
and
.I \-v
options will apply to this match.
.IP "\-g geometry"
apply a geometry (using a standard X geometry string) to applications matching
the last
.I \-app.
.IP "\-v vdesk"
specify a default virtual desktop for applications matching the last
.I \-app.
Note that desktops are numbered from 0.
.IP "\-s"
specify that application is to start with a sticky client window.
.IP "\-nosoliddrag"
draw a window outline while moving or resizing.
.IP "\-V"
print version number.
.SH BUGS
The author's idea of friendly may differ to that of many other people.
.SH AUTHOR
Ciaran Anscomb <evilwm@6809.org.uk>.
.br
aewm was written by Decklin Foster <fosterd@hartwick.edu>.
.br
9wm was written by David Hogan <dhog@cs.su.oz.au>.
.SH "SEE ALSO"
.BR xterm (1),
.BR xprop (1)
